version: '3'

services:
  web-scrap-script:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/athletes_successes
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - postgres_DB=athletes_successes
      - FORCE_SETUP=${FORCE_SETUP:-false}
  postgres:
    build: ./postgresql
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: