version: 3:latest

services:
  web-srap-script:
    build: .
    volumes:
      - .:/athletes_successes
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - postgres_DB=athletes_successes
  postgres:
    build: ./postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: